# Generated by Django 3.2.8 on 2022-04-04 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xmaspops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='popup',
            name='text_color',
            field=models.CharField(default='#000000', max_length=60),
        ),
        migrations.AlterField(
            model_name='popup',
            name='theme',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xmaspops.theme'),
        ),
    ]
