# Generated by Django 3.2.8 on 2021-10-28 14:00

import cardadds.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=cardadds.models.save_image_location)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Card Categories',
            },
        ),
        migrations.CreateModel(
            name='CardAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, max_length=12, unique=True)),
                ('business_name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, default='Merry Christmas Happy New Year', max_length=200)),
                ('content', models.TextField(blank=True, default='We would like to wish all our valuable customers a Merry Christmas and Happy New Year and Holiday Season!', verbose_name='message content')),
                ('promotion', models.CharField(blank=True, default='up to 30% off', max_length=250, verbose_name='promotional offer')),
                ('business_reinstatement', models.TextField(blank=True, default='We will be closed for the Christmas Season From 24th December to the 2nd January')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardadds.cardcategory')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardadds.backgroundimage', verbose_name='background theme')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
