# Generated by Django 3.2.8 on 2021-10-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardadds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardadd',
            name='ref_code',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
