# Generated by Django 3.2.8 on 2021-10-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardadds', '0003_cardcategory_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardadd',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
    ]
