# Generated by Django 3.2.8 on 2021-10-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardadds', '0003_auto_20211023_0752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardadd',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='cardcategory',
            options={'verbose_name_plural': 'Card Categories'},
        ),
    ]
