# Generated by Django 3.2.8 on 2021-10-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardadds', '0004_auto_20211023_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardadd',
            name='content',
            field=models.TextField(verbose_name='message content'),
        ),
    ]
