# Generated by Django 3.2.8 on 2021-10-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardadds', '0004_cardadd_is_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardadd',
            options={'ordering': ['-created', '-updated']},
        ),
        migrations.AlterField(
            model_name='cardadd',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cardadd',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
