# Generated by Django 3.2.8 on 2021-11-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardadds', '0005_auto_20211030_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardadd',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RemoveField(
            model_name='cardadd',
            name='promotion',
        ),
        migrations.AddField(
            model_name='cardadd',
            name='closing_content',
            field=models.TextField(blank=True, default='and Holiday Season!'),
        ),
        migrations.AddField(
            model_name='cardadd',
            name='promotion_content',
            field=models.CharField(blank=True, default='For the months of December and January we are running the following Special:', max_length=250, verbose_name='promotional content'),
        ),
        migrations.AddField(
            model_name='cardadd',
            name='promotional_offer',
            field=models.CharField(blank=True, default='up to 30% off', max_length=50),
        ),
        migrations.AlterField(
            model_name='cardadd',
            name='content',
            field=models.TextField(blank=True, default='We would like to wish all our valuable customers a', verbose_name='message content'),
        ),
        migrations.AlterField(
            model_name='cardadd',
            name='title',
            field=models.CharField(blank=True, default='Merry Christmas & Happy New Year', max_length=200),
        ),
    ]
