# Generated by Django 3.2.8 on 2021-10-24 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardadds', '0005_alter_cardadd_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardadd',
            name='card_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cardadd',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardadds.backgroundimage', verbose_name='background theme'),
        ),
    ]
