# Generated by Django 3.2.8 on 2021-11-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardadds', '0006_auto_20211103_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardadd',
            name='promotion_content',
            field=models.TextField(blank=True, default='For the months of December and January we are running the following Special:', max_length=250, verbose_name='promotional content'),
        ),
    ]
