# Generated by Django 3.2.8 on 2021-10-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardadds', '0006_auto_20211024_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardadd',
            name='business_reinstatement',
            field=models.TextField(default='We will be closed for the Christmas Season From 24th December to the 2nd January'),
        ),
        migrations.AlterField(
            model_name='cardadd',
            name='content',
            field=models.TextField(default='We would like to wish all our valuable customers a Merry Christmas and Happy New Year and Holiday Season!', verbose_name='message content'),
        ),
        migrations.AlterField(
            model_name='cardadd',
            name='promotion',
            field=models.CharField(default='up to 30% off', max_length=250, verbose_name='promotional offer'),
        ),
        migrations.AlterField(
            model_name='cardadd',
            name='title',
            field=models.CharField(default='Merry Christmas Happy New Year', max_length=200),
        ),
    ]
