# Generated by Django 3.2.8 on 2021-10-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardadds', '0007_auto_20211025_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardadd',
            name='base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
