# Generated by Django 3.2.8 on 2021-11-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardadds', '0007_alter_cardadd_promotion_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardadd',
            name='business_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cardadd',
            name='content',
            field=models.TextField(blank=True, default='We would like to wish all our valuable customers a', verbose_name='start content'),
        ),
        migrations.AlterField(
            model_name='cardadd',
            name='promotion_content',
            field=models.TextField(blank=True, default='For the months of December and January we are running the following Special:', verbose_name='promotional content'),
        ),
        migrations.AlterField(
            model_name='cardadd',
            name='title',
            field=models.CharField(blank=True, default='Merry Christmas & Happy New Year', max_length=100, verbose_name='content title'),
        ),
    ]
