# Generated by Django 3.2.8 on 2021-10-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardadds', '0008_cardadd_base64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardadd',
            name='base64',
        ),
        migrations.AddField(
            model_name='backgroundimage',
            name='base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
