# Generated by Django 3.2.8 on 2021-10-27 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardadds', '0010_auto_20211027_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundimage',
            name='base64',
        ),
    ]
